apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-project
  namespace: default
  labels:
    app: java-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-project
  template:
    metadata:
      labels:
        app: java-project
    spec:
      containers:
        - name: java-project
          image: manishasasi5/java-project:26
          ports:
            - containerPort: 8080
